name: EWS_env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _pytorch_select=0.1
  - absl-py=1.3.0
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - async-timeout=4.0.2
  - asynctest=0.13.0
  - attrs=22.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=2.0.0
  - binutils_impl_linux-64=2.38
  - blas=1.0
  - blinker=1.4
  - blosc=1.21.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.1.31
  - cachetools=4.2.2
  - cairo=1.14.12
  - certifi=2024.8.30
  - cffi=1.15.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cloudpickle=2.0.0
  - colorama=0.4.6
  - cryptography=39.0.1
  - cudatoolkit=11.0.221
  - cupy=11.2.0
  - cxxfilt=0.3.0
  - cytoolz=0.12.0
  - dask-core=2021.10.0
  - debugpy=1.6.3
  - decorator=5.1.1
  - entrypoints=0.4
  - expat=2.6.3
  - fastrlock=0.8
  - ffmpeg=4.0
  - flit-core=3.6.0
  - fontconfig=2.14.1
  - freeglut=3.4.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - fsspec=2022.11.0
  - future=0.18.3
  - gcc=12.1.0
  - gcc_impl_linux-64=12.1.0
  - giflib=5.2.1
  - glib=2.56.2
  - google-auth-oauthlib=0.4.4
  - graphite2=1.3.14
  - grpc-cpp=1.48.1
  - grpcio=1.46.3
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - idna=3.4
  - imagecodecs=2021.8.26
  - imageio=2.19.3
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - iniconfig=1.1.1
  - intel-openmp=2019.4
  - ipykernel=6.16.2
  - ipython=7.33.0
  - jasper=2.0.14
  - jedi=0.19.1
  - jpeg=9e
  - jupyter_client=7.4.9
  - jupyter_core=4.11.1
  - jxrlib=1.1
  - kernel-headers_linux-64=3.10.0
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libabseil=20220623.0
  - libaec=1.0.4
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.88.1
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc=14.1.0
  - libgcc-devel_linux-64=12.1.0
  - libgcc-ng=14.1.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgfortran5=14.1.0
  - libglu=9.0.0
  - libgomp=14.1.0
  - liblapack=3.9.0
  - libmklml=2019.0.5
  - libnghttp2=1.57.0
  - libnsl=2.0.0
  - libopencv=3.4.2
  - libopus=1.3.1
  - libpng=1.6.39
  - libprotobuf=3.21.8
  - libsanitizer=12.1.0
  - libsodium=1.0.18
  - libssh2=1.11.0
  - libstdcxx=14.1.0
  - libstdcxx-ng=12.3.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libvpx=1.7.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxml2=2.10.4
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - locket=1.0.0
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.7
  - mkl=2020.2
  - multidict=6.0.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=2.6.3
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.21.6
  - nvidia-apex=0.1
  - oauthlib=3.2.1
  - opencv=3.4.2
  - openjpeg=2.5.2
  - openssl=3.4.0
  - packaging=22.0
  - parso=0.8.4
  - partd=1.2.0
  - pcre=8.45
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=21.2.2
  - pixman=0.40.0
  - pluggy=1.0.0
  - prompt-toolkit=3.0.47
  - ptyprocess=0.7.0
  - py=1.11.0
  - py-opencv=3.4.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pydensecrf=1.0rc3
  - pygments=2.17.2
  - pyjwt=2.4.0
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - pytest=7.1.2
  - python=3.7.12
  - python_abi=3.7
  - pytorch=1.7.1
  - pytorch-lightning=1.5.10
  - pyu2f=0.1.5
  - pywavelets=1.3.0
  - pyyaml=6.0
  - pyzmq=24.0.1
  - re2=2022.06.01
  - readline=8.2
  - requests=2.28.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-image=0.19.3
  - six=1.16.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - sysroot_linux-64=2.17
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tifffile=2021.7.2
  - tk=8.6.14
  - tomli=2.0.1
  - toolz=0.12.0
  - torchmetrics=0.10.3
  - tornado=6.2
  - traitlets=5.9.0
  - typing_extensions=4.4.0
  - tzdata=2024a
  - urllib3=1.26.14
  - wcwidth=0.2.10
  - werkzeug=2.2.2
  - wheel=0.38.4
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.8.1
  - zeromq=4.3.5
  - zfp=0.5.5
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - annotated-types==0.5.0
      - antlr4-python3-runtime==4.9.3
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - comm==0.1.4
      - cycler==0.11.0
      - cython==3.0.11
      - dacite==1.8.1
      - easydict==1.13
      - fonttools==4.38.0
      - google-auth==1.35.0
      - htmlmin==0.1.12
      - hydra-core==1.3.2
      - imagehash==4.3.1
      - importlib-resources==5.12.0
      - iprogress==0.4
      - ipywidgets==8.1.5
      - jinja2==3.1.4
      - joblib==1.3.2
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.5
      - kornia==0.5.8
      - llvmlite==0.39.1
      - matplotlib==3.5.3
      - minio==7.2.7
      - multimethod==1.9.1
      - numba==0.56.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - omegaconf==2.3.0
      - opencv-python==4.10.0.84
      - pandas==1.3.5
      - pandas-profiling==3.6.6
      - patsy==1.0.1
      - phik==0.12.3
      - polars==0.18.4
      - protobuf==3.6.0
      - psutil==5.8.0
      - pycryptodome==3.21.0
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - pydeprecate==0.3.1
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - scikit-learn==1.0.2
      - scipy==1.5.4
      - seaborn==0.12.2
      - setuptools==59.5.0
      - statsmodels==0.13.5
      - tangled-up-in-unicode==0.2.0
      - tensorboard==2.4.0
      - threadpoolctl==3.1.0
      - torch==1.7.1
      - torchaudio==0.7.2
      - torchpq==0.3.0.6
      - torchvision==0.8.2
      - tqdm==4.59.0
      - typeguard==4.1.2
      - typing-extensions==4.7.1
      - visions==0.7.5
      - wget==3.2
      - widgetsnbextension==4.0.13
      - wordcloud==1.9.4
      - ydata-profiling==4.12.1

